### ISSUE TITLE
Questions about cmake

### ISSUE THREAD

**Issue by star-123456** [Hsin-Hung/aby3#1]
Hello, I'm executing
python3 build. py --setup
The following error is reported during this command:
![ee585da3c2182570f7a765e89bd37c2](https://user-images.githubusercontent.com/67616517/149258046-fb7ac457-1d7c-46a0-8899-25b849d27741.png)
While executing
python3 build. py
The following errors are reported:
![3bd3a4180598d1350a8dd808540ba19](https://user-images.githubusercontent.com/67616517/149258089-87ad5f98-aef8-4103-a2a7-a56ee78a9a36.png)
Why is this problem? Please help me!

**Comment by sunnycomes** [comment]
install cmake will fix this problem.
